# Copyright (c) 2026 LightSeek Foundation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""V4.1 Flash: four history groups sharing one 1,382,400-byte LCM plane.

Only source layers own global fields; Reuse/Reindex layers read those views.
The FP32 compressor input is position-addressed history, not a mutable
per-request ring. Allocation, protection, and reclamation therefore stay in
LCM, including odd-token chunk boundaries. Prefix matching covers the two
global groups only: the SWA and compressor-tail groups declare
``replay_window_tokens`` and are regenerated by bounded replay -- the
scheduler re-feeds the cached prefix's last window ahead of a hit and the
backend rebuilds their rows there, never publishing them.
"""

from collections.abc import Mapping, Sequence

from typing_extensions import override

from tokenspeed.runtime.layers.attention.configs.deepseek_v41 import DeepseekV41Config
from tokenspeed.runtime.layers.attention.deepseek_v41_geometry import (
    V41_COMPRESSOR_TAIL_GROUP_ID,
    V41_DSPARK_GROUP_PACKING,
    V41_DSPARK_LCM_BLOCK_BYTES,
    V41_GLOBAL_R1_GROUP_ID,
    V41_GLOBAL_R2_GROUP_ID,
    V41_GLOBAL_ROW_BYTES,
    V41_GROUP_GEOMETRY,
    V41_GROUP_PACKING,
    V41_HEAD_DIM,
    V41_INDEX_HEAD_DIM,
    V41_INDEX_ROW_BYTES,
    V41_LCM_BLOCK_BYTES,
    V41_PREFILL_QUERY_TILE,
    V41_SWA_GROUP_ID,
    V41_SWA_ROW_BYTES,
    V41_WINDOW_SIZE,
    v41_dspark_field_name,
    v41_layer_mapping,
    v41_table_widths,
)
from tokenspeed.runtime.layers.attention.kv_cache.recipes.base import CacheRecipe
from tokenspeed.runtime.layers.attention.kv_cache.recipes.plan import (
    CacheFieldSpec,
    CacheLayout,
)
from tokenspeed.runtime.layers.attention.kv_cache.recipes.spec import (
    CacheGroupDeclaration,
    CacheGroupSpec,
    apply_pd_transfer_policies,
)


class DeepseekV41Recipe(CacheRecipe):
    """Target Flash FlatKV for decode/verify, plus checkpoint-local DSpark windows.

    Verify width changes retention and workspace, never the target field layout.
    A same-checkpoint DSpark draft keeps its per-stage context window as extra
    fields of the SWA group on the last target layer: one row per position,
    addressed by the target's SWA slots, cached, transferred and evicted with
    the SWA rows. The parent grows and the other groups repack accordingly.
    """

    family = "deepseek_v41"

    @property
    @override
    def layer_types(self) -> tuple[str, ...]:
        return ("sliding_attention",) * self.num_target_layers

    @property
    @override
    def max_padding_fraction(self) -> float:
        return 0.05

    def dspark_stages(self) -> int:
        """Number of same-checkpoint DSpark draft stages, 0 without DSpark."""
        if (
            getattr(self.server_args, "speculative_algorithm", None) != "DSPARK"
            or self.draft_model_config is None
            or self.draft_attn_config is not None
        ):
            return 0
        hf = self.draft_model_config.hf_config
        hf = getattr(hf, "text_config", hf)
        stages = int(getattr(hf, "dspark_num_stages", 0))
        if stages < 1:
            raise ValueError("DeepSeek V4.1 DSpark requires a positive stage count")
        return stages

    @override
    def groups(self) -> tuple[CacheGroupDeclaration, ...]:
        if self.num_draft_layers:
            raise NotImplementedError(
                "DeepSeek V4.1 FlatKV stores target layers only; draft attention "
                "layers are not supported"
            )
        if self.decode_input_tokens < 1:
            raise ValueError("DeepSeek V4.1 verify width must be positive")
        if int(self.server_args.pipeline_parallel_size) != 1:
            raise NotImplementedError("DeepSeek V4.1 shared-owner FlatKV requires PP=1")
        hf = self.model_config.hf_config
        hf = getattr(hf, "text_config", hf)
        ratios = tuple(int(r) for r in hf.compress_ratios[: self.num_target_layers])
        owners = tuple(int(layer) for layer in hf.kv_source_layers)
        if (
            self.num_target_layers != 40
            or int(hf.head_dim) != V41_HEAD_DIM
            or int(hf.index_head_dim) != V41_INDEX_HEAD_DIM
            or int(hf.sliding_window) != V41_WINDOW_SIZE
            or len(ratios) != self.num_target_layers
            or any(r not in (0, 1, 2) for r in ratios)
            or owners != (2, 8, 14, 20)
            or tuple(ratios[layer] for layer in owners) != (2, 2, 2, 1)
        ):
            raise ValueError(
                "DeepSeek V4.1 FlatKV packing requires the Flash cache geometry"
            )
        v41_layer_mapping(
            ratios,
            owners,
            tuple(hf.index_source_layers),
            int(hf.candidate_source_layer),
        )
        if self.prefix_granularity <= 0 or any(
            self.prefix_granularity % (rows * stride)
            for rows, stride in V41_GROUP_GEOMETRY.values()
        ):
            raise ValueError(
                "DeepSeek V4.1 prefix granularity must be a positive multiple of 128"
            )

        fields: dict[str, list[CacheFieldSpec]] = {
            gid: [] for gid in V41_GROUP_GEOMETRY
        }

        def add(
            gid: str, layer: int, name: str, shape: tuple[int, ...], dtype: str
        ) -> None:
            fields[gid].append(
                CacheFieldSpec(
                    field_id=f"layer.{layer}.{name}",
                    plane_id="flatkv",
                    shape=shape,
                    dtype=dtype,
                    exact_page_stride=False,
                    page_stride_alignment_bytes=512 if name == "swa" else 256,
                )
            )

        for layer in range(self.num_target_layers):
            add(V41_SWA_GROUP_ID, layer, "swa", (64, V41_SWA_ROW_BYTES), "uint8")
        # The draft reads each stage's window with the target's SWA slots, so
        # the rows live in the SWA group; the last target layer owns the field
        # ids, so PD and L2 treat them as target state produced with that layer.
        for stage in range(self.dspark_stages()):
            add(
                V41_SWA_GROUP_ID,
                self.num_target_layers - 1,
                v41_dspark_field_name(stage),
                (64, V41_HEAD_DIM),
                "bfloat16",
            )
        for owner in owners:
            gid = (
                V41_GLOBAL_R2_GROUP_ID if ratios[owner] == 2 else V41_GLOBAL_R1_GROUP_ID
            )
            add(gid, owner, "global_kv", (64, V41_GLOBAL_ROW_BYTES), "uint8")
            add(gid, owner, "index_k", (64, V41_INDEX_ROW_BYTES), "uint8")
            if ratios[owner] == 2:
                add(
                    V41_COMPRESSOR_TAIL_GROUP_ID,
                    owner,
                    "compressor_tail",
                    (2, 2, V41_HEAD_DIM),
                    "float32",
                )

        # Admission can be ahead of the completed forward. Retain its input
        # window as well as the unfinished pair; the allocator also reserves
        # in-flight pages through the shared scheduler_limits demand formula.
        # The window is part of the PD peer contract, so size it for the
        # deepest schedule (depth 1) on every role: a prefill node runs without
        # overlap, and its pages must land in a decode node's retention.
        protection = 2 * self.decode_input_tokens
        windows = {
            V41_SWA_GROUP_ID: V41_WINDOW_SIZE + protection,
            V41_GLOBAL_R2_GROUP_ID: None,
            V41_GLOBAL_R1_GROUP_ID: None,
            V41_COMPRESSOR_TAIL_GROUP_ID: 2 + protection,
        }
        # SWA rows and compressor tails are never prefix-cached: a hit on the
        # global groups re-feeds the last window of the cached prefix and the
        # model regenerates them (bounded replay). SWA needs the whole
        # attention window before a boundary; a compressor tail only the
        # unfinished pair. The regenerated rows see SWA keys from the replay
        # start only -- not the stacked receptive field the original prefill
        # had -- which is the truncation the model is trained for (tech report
        # 2.2); the shared global KV is never recomputed from them.
        replays = {
            V41_SWA_GROUP_ID: V41_WINDOW_SIZE,
            V41_GLOBAL_R2_GROUP_ID: None,
            V41_GLOBAL_R1_GROUP_ID: None,
            V41_COMPRESSOR_TAIL_GROUP_ID: 2,
        }
        specs = [
            CacheGroupSpec(
                group_id=gid,
                retention=(
                    "full_history" if windows[gid] is None else "sliding_window"
                ),
                rows_per_page=rows,
                entry_stride_tokens=stride,
                sliding_window_tokens=windows[gid],
                replay_window_tokens=replays[gid],
                family="history",
                transfer_policy=None,
                checkpoint_granularity=None,
            )
            for gid, (rows, stride) in V41_GROUP_GEOMETRY.items()
        ]
        if self.pd_disaggregation_enabled:
            specs = apply_pd_transfer_policies(specs)
        return tuple((spec, tuple(fields[spec.group_id])) for spec in specs)

    def _group_packing(self) -> Mapping[str, int]:
        return V41_DSPARK_GROUP_PACKING if self.dspark_stages() else V41_GROUP_PACKING

    def _lcm_block_bytes(self) -> int:
        return (
            V41_DSPARK_LCM_BLOCK_BYTES if self.dspark_stages() else V41_LCM_BLOCK_BYTES
        )

    @override
    def packing(self, groups: Sequence[CacheGroupDeclaration]) -> Mapping[str, int]:
        packing = self._group_packing()
        return {spec.group_id: packing[spec.group_id] for spec, _ in groups}

    @override
    def check_layout(self, layout: CacheLayout) -> None:
        expected = self._lcm_block_bytes()
        if layout.lcm_block_bytes != expected or len(layout.plane_bytes) != 1:
            raise ValueError(
                f"DeepSeek V4.1 Flash requires one {expected:,}-byte plane"
            )

    @override
    def num_lcm_blocks(self, layout: CacheLayout) -> int:
        budgeted = self._budgeted_parents(
            self.cache_budget_bytes - self.workspace_bytes(), layout.lcm_block_bytes
        )
        return self.parents_needed(layout, self.token_capacity(layout, budgeted))

    @override
    def token_capacity(self, layout: CacheLayout, num_lcm_blocks: int) -> int:
        return self._capacity_from_parents(
            layout,
            num_lcm_blocks,
            upper_bound=(
                self.token_limit
                if self.token_limit is not None
                else num_lcm_blocks * self._group_packing()[V41_GLOBAL_R1_GROUP_ID] * 64
            ),
        )

    @override
    def workspace_bytes(self) -> int:
        """Reserve decode tables and bounded per-forward index/attention scratch.

        The kernel baseline tiles queries; it must never gather all selected
        BF16 KV rows for an entire prefill at once. Candidate/top-k ids still
        live for every scheduled query across Reindex/Reuse layers.
        """
        max_bs = self.attn_config.max_bs
        horizon = (1 + self.overlap_schedule_depth) * self.decode_input_tokens
        tables = (
            4
            * max_bs
            * sum(v41_table_widths(self.attn_config.context_len, horizon).values())
        )
        queries = self.attn_config.component(DeepseekV41Config).max_query_tokens
        # Tables/lengths stay request-shaped; positions, request maps, write
        # locations and compact SWA slots/lengths cover every verify query.
        # Budget extend plus persistent decode views.
        metadata = 2 * (tables + max_bs * 32 + queries * (64 + 128 * 4 + 4) + 4)
        # Both MIXED windows together are bounded by queries. Include the
        # packed current SWA rows and two generations of selection records.
        selections = queries * ((2048 + 2 * 512 + 128) * 8 + 528)
        spec = self.attn_config.component(DeepseekV41Config)
        local_heads = spec.num_attention_heads // spec.attn_tp_size
        padded_heads = 64 if local_heads <= 64 else 128
        query_tile = min(queries, V41_PREFILL_QUERY_TILE)
        # Native Q and output coexist for one tile. Previous tiles release the
        # padded result after copying their real heads into the final output.
        native_attention = 2 * query_tile * padded_heads * V41_HEAD_DIM * 2
        real_output = queries * local_heads * V41_HEAD_DIM * 2
        # One request at a time shares its prefix/current/global BF16 workspace.
        # The ratio-1 group is the upper bound for any compressed history.
        compact_kv = (
            (self.attn_config.context_len + queries + max_bs * V41_WINDOW_SIZE)
            * V41_HEAD_DIM
            * 2
        )
        # BF16 current SWA and compact [T,128+512] indices coexist with that KV.
        compact_metadata = queries * (V41_HEAD_DIM * 2 + (128 + 512) * 4)
        # Packed index Q (32 global heads, 64 value + 4 scale bytes) and a
        # 32-MiB logits tile plus selection copies; score/selection is bounded
        # independently of the complete context or the prefill query count.
        index_queries = queries * 32 * (128 * 2 + 68)
        score_columns = (self.attn_config.context_len + 63) // 64 * 64
        score_scratch = min(128 << 20, min(queries, 1024) * score_columns * 4)
        block_k = max(32, 1 << (min(2048, max(1, score_columns // 8)) - 1).bit_length())
        # Sixteen portable partitions plus bounded TopK merge temporaries.
        portable_scratch = min(queries, 256) * 24 * (512 + block_k) * 12
        index_selection = max(3 * score_scratch, portable_scratch) + score_columns * 68
        # Ratio-2 pooling returns T FP32 rows, including inactive (-1) positions.
        compressor_output = queries * V41_HEAD_DIM * 4
        return (
            metadata
            + selections
            + compressor_output
            + native_attention
            + real_output
            + compact_kv
            + compact_metadata
            + index_queries
            + index_selection
        )
